{% set shortversion = "7.0" %}
{% set version = "7.0.0" %}
{% set sha256 = "8bc1f844e6cbde1b652c19c1edebc1864456fd9c78b8c1bea038e51b363fe222" %}
{% set build_number = "0" %}


package:
  name: llvmdev
  version: {{ version }}

source:
  fn: llvm-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    # http://lists.llvm.org/pipermail/llvm-dev/2016-January/094520.html
    - ../llvm-lto-static.patch   # [win]
    # Intel SVML optimizations
    - ../D47188-svml-VF.patch
    # undefined behavior bug due to Twine usage
    - ../twine_cfg_undefined_behavior.patch

build:
  number: {{ build_number }}
  string: "manylinux1h{{ PKG_HASH }}"
  script_env:
    - CFLAGS
    - CXXFLAGS
    - PY_VCRUNTIME_REDIST

requirements:
  build:
    - cmake
    # Needed to unpack the source tarball
    - m2w64-xz         # [py27 and win]
    # Needed to build LLVM
    - python

test:
  commands:
    - $PREFIX/bin/llvm-config --libs                         # [not win]
    - $PREFIX/bin/llc -version                               # [not win]

    - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1        # [win]
    - if not exist %LIBRARY_LIB%\\LLVMSupport.lib exit 1     # [win]

    - test -f $PREFIX/include/llvm/Pass.h                    # [unix]
    - test -f $PREFIX/lib/libLLVMSupport.a                   # [unix]

    - test -f $PREFIX/lib/libLLVMCore.a                      # [not win]

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM
