parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 11
    matrix:
      py27:
        PYTHON: '2.7'
        CONDA_ENV: travisci
      py37:
        PYTHON: '3.7'
        CONDA_ENV: travisci

  steps:
    - task: CondaEnvironment@1
      inputs:
        updateConda: no
        packageSpecs: ''

    # Need to install VC 9.0 only for Python 2.7
    - powershell: |
        $wc = New-Object net.webclient
        $wc.Downloadfile("https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi", "VCForPython27.msi")
        Start-Process "VCForPython27.msi" /qn -Wait
      displayName: 'Install VC 9.0'
      condition: eq(variables['PYTHON'], '2.7')

    - script: |
        buildscripts\\incremental\\setup_conda_environment.cmd
      displayName: 'Before Install'

    - script: |
        buildscripts\\incremental\\build.cmd
      displayName: 'Build'

    - script: |
        buildscripts\\incremental\\test.cmd
      displayName: 'Test'
